import Header from './components/Header';
import Footer from './components/Footer';
import { Inter } from 'next/font/google';
import AuthProvider from './AuthProvider';
import './styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <AuthProvider>
            <html lang="en" className={inter.className}>
                <body className="min-h-screen overflow-x-hidden bg-gradient-to-b from-slate-900 from-10% to-slate-800 to-90% bg-cover text-white">
                    <Header />
                    <main>{children}</main>
                    <Footer />
                </body>
            </html>
        </AuthProvider>
    );
};

export default RootLayout;
